// <auto-generated />
using AspNetCoreApps.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreApps.Migrations
{
    [DbContext(typeof(ExStudentDbContext))]
    [Migration("20191209065611_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetCoreApps.Models.Student", b =>
                {
                    b.Property<int>("StudentRowId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseName")
                        .IsRequired();

                    b.Property<string>("StudentId")
                        .IsRequired();

                    b.Property<string>("StudentName")
                        .IsRequired();

                    b.Property<int>("UniversityRowId");

                    b.HasKey("StudentRowId");

                    b.HasIndex("UniversityRowId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AspNetCoreApps.Models.University", b =>
                {
                    b.Property<int>("UniversityRowId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<string>("UniversityId")
                        .IsRequired();

                    b.Property<string>("UniversityName")
                        .IsRequired();

                    b.HasKey("UniversityRowId");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("AspNetCoreApps.Models.Student", b =>
                {
                    b.HasOne("AspNetCoreApps.Models.University", "University")
                        .WithMany("Students")
                        .HasForeignKey("UniversityRowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
